config/routes.rb
Rails.application.routes.draw do
	resources :communities
	devise_for :users, controllers: { registrations: 'users/registrations' }

	get '/license/get/:majorid' => 'license#getlicenselist'
	post '/license/get/' => 'license#getlicenselist'
	
	root :to => "home#index"
	match ":controller(/:action(/:id))", :via => [:post, :get]

	post "/license/create/" => "license#create"
	post "/license/:type/:id" => "license#update"
	delete "/license/:type/:id" => "license#destroy"

	# get "/license/:id" => "license#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    mount_uploader :pic, ImageUploader
    has_many :book_comments
	belongs_to :user
	is_impressionable
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :book
	belongs_to :user
end

app/models/community.rb
class Community < ApplicationRecord
    has_many :community_comments
	belongs_to :user
    is_impressionable #:counter_cache => true
end

app/models/community_comment.rb
class CommunityComment < ApplicationRecord
    belongs_to :community
	belongs_to :user
end

app/models/got_license.rb
class GotLicense < ApplicationRecord
    has_many :bridge_got_container_and_licenses
	has_many :got_license_containers, through: :bridge_got_container_and_licenses
end

app/models/license.rb
class License < ApplicationRecord
	has_many :bridge_aim_container_and_licenses
	has_many :aim_license_containers, through: :bridge_aim_container_and_licenses

	has_many :bridge_like_container_and_licenses
	has_many :like_license_containers, through: :bridge_like_container_and_licenses

	has_many :bridge_got_container_and_licenses
	has_many :got_license_containers, through: :bridge_got_container_and_licenses

	has_many :test_schedules
	
	has_many :bridge_major_and_licenses
	has_many :majors, through: :bridge_major_and_licenses
end

app/models/major.rb
class Major < ApplicationRecord
	has_many :users
    
    has_many :bridge_major_and_licenses
	has_many :licenses, through: :bridge_major_and_licenses
end

app/models/test_schedule.rb
class TestSchedule < ApplicationRecord
    belongs_to :license
	has_many :written_test_schedules
	has_many :practice_test_schedules
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :major

  has_one :aim_license_container
  has_one :like_license_container
  has_one :got_license_container

  has_many :anony_posts
  has_many :anony_comments
  has_many :book_posts
  has_many :book_comments

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show, :index], unique: [:session_hash]
  
  # GET /books
  # GET /books.json
  def index
    if user_signed_in?
      @books = Book.all.paginate(:page => params[:page], per_page: 6).order("id desc")
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    impressionist(@book)
  end



  # GET /books/new
  def new
    @book = Book.new
  end



  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user
    uploader = ImageUploader.new  # 새로운 머신 업로더를 생성하고
    uploader.store!(params[:pic]) # 받아온 이미지를 저장하고 
    @book.image_url = uploader.url # 그 url 값을 @book.imgage_url에 저장한다
  
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: '글을 성공적으로 작성하였습니다' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: '글이 수정되었습니다' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: '글이 삭제되었습니다' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :content, :price)
    end
  
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show, :index], unique: [:session_hash]

  # GET /communities
  # GET /communities.json
  def index
    if user_signed_in?
      @communities = Community.all.paginate(:page => params[:page], per_page: 5).order("id desc")
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @community = Community.find(params[:id])
    impressionist(@community)
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)
    
    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: '글을 성공적으로 작성하였습니다' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: '글이 수정되었습니다' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: '글이 삭제되었습니다' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:title, :content)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
          redirect_to '/license/myAim'
    else
          render layout: 'index'
    end
  end
  
  def main
    
  end
 
  def search
    @searchResult = License.all
    if params[:search]
        @searchResult = License.search(params[:search]).order("created_at DESC")
    else
        @searchResult = License.all.order('created_at DESC')
    end
  end

  def calendar

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
    end

    def resource
        @user ||= User.new
    end
  
    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/license_helper.rb
module LicenseHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/views/communities/_form.html.erb
<%= form_for(community) do |f| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>
      <ul>
      <% community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!--%= f.label :title %--->
    <%= f.text_field :title, :required => true, placeholder: "제목을 입력해주세요." %>
  </div>

  <div class="field">
    <!--%= f.label :content %--->
    <%= f.text_area :content, :required => true, :class => "com-new", placeholder: "내용을 입력해주세요." %>
  </div>

  <div class="actions">
    <%= f.submit "작성",  class: "btn btn-community" %>
    <%= link_to '목록', communities_path,  class: "btn btn-community" %>
  </div>
  
  <% end %>

app/views/communities/edit.html.erb
<div class="container">
  <div class="community">

<%= render 'form', community: @community %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

 </div>
</div>

app/views/communities/index.html.erb
<div class="container">
  <div class="community">
    <p id="notice"><%= notice %></p>
    <table class="centered bordered">
      <thead>
        <tr>
          <th width="70">번호</th>
          <th align="center">제목</th>
          <th width="130">날짜</th>
          <th width="80">조회수</th>
        </tr>
      </thead>
    
      <tbody>
        <% @communities.each do |community| %>
          <tr>
            <td><%= community.id %></td>
            <td><strong><a href="communities/<%=community.id %>"><%= community.title %></a></strong></td>
            <td><%= community.created_at.strftime("%Y-%m-%d") %></td>
            <td><%= community.impressions.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <!---- 페이지네이션 ----->
    <div class="row center">
      <!--ul id="pagination-community" class="pagination center">
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
        <li class="active"><a href="/communities?page=1">1</a></li>
        <li class="waves-effect"><a href="/communities?page=2">2</a></li>
        <li class="waves-effect"><a href="/communities?page=3">3</a></li>
        <li class="waves-effect"><a href="/communities?page=4">4</a></li>
        <li class="waves-effect"><a href="#!">5</a></li>
        <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
      </ul-->
      <!--- ↑ metarialize --->
      <%= will_paginate @communities, :previous_label => '<' , :next_label => '>' %>
    </div>
    <br>
    <div class="btn-wrapper">
    <%= link_to '글쓰기', new_community_path, class: "btn btn-community" %>  
    </div>
  </div>
</div>


    
    
<!----script type="text/javascript">
     
  $(document).ready(function(){
    $('#pagination-community').pagination({
        dataSource: [1, 2, 3, 4, 5, 6, 7, ... , 35],
        pageSize: 5,
        pageNumber: 3,
        callback: function(data, pagination) {
            // template method of yourself
            var html = template(data);
            dataContainer.html(html);
        }
    })
    });
</script--->

app/views/communities/new.html.erb
<div class="container">
  <div class="community">
    
    <%= render 'form', community: @community %>
    
  </div>
</div>

app/views/communities/show.html.erb
<div class="container">
  <div class="community">
    <p id="notice"><%= notice %></p>
    
    <p>
      <h5><%= @community.title%></h5>
    </p>
    <hr>
  
    <p class="com-content">
      <%= @community.content %>
    </p>
    
    <p>
      조회수 : <%= @community.impressions.count %>
    </p>
  
    <%= link_to '수정', edit_community_path(@community),  class: "btn btn-community" %> |
    <%= link_to '삭제', @community, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-community" %> |
    <%= link_to '목록', communities_path,  class: "btn btn-community" %> 
  </div>
</div>